# Generated by Django 5.2.5 on 2025-10-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='labs.lab'),
        ),
    ]
